project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls')),
]

project_tracker/quality_control/urls.py
#Function-Based Views
from django.urls import path
from . import views

app_name = 'quality_control'

urlpatterns = [
    path('', views.index, name='index'),
    path('bugreports/', views.bugreport_list, name='bugreport_list'),
    path('bugreports/<int:pk_id>/', views.bugreport_detail, name='bugreport_detail'),
    path('featurerequests/', views.featurerequest_list, name='featurerequest_list'),
    path('featurerequests/<int:pk_id>/', views.featurerequest_detail, name='featurerequest_detail'),
    path('bugreport_create/', views.bugreport_create, name='bugreport_create'),
    path('featurerequest_create/', views.featurerequest_create, name='featurerequest_create'),
    path('bugreports/<int:pk_id>/update/', views.bugreport_update, name='bugreport_update'),
    path('bugreports/<int:bugreport_id>/delete/', views.bugreport_delete, name='bugreport_delete'),
    path('featurerequests/<int:pk_id>/update/', views.featurerequest_update, name='featurerequest_update'),
    path('featurerequests/<int:featurerequest_id>/delete/', views.featurerequest_delete, name='featurerequest_delete'),
   ]


# #Class-Based Views
#
# from django.urls import path
# from . import views
#
#
# app_name = 'quality_control'
#
# urlpatterns = [
#     path('', views.IndexView.as_view(), name='index'),
#     path('bugreports/', views.BugReportListView.as_view(), name='bugreport_list'),
#     path('featurerequests/', views.FeatureRequestListView.as_view(), name='featurerequest_list'),
#     path('bugreports/<int:pk_id>/', views.BugReportDetailView.as_view(), name='bugreport_detail'),
#     path('featurerequests/<int:pk_id>/', views.FeatureRequestDetailView.as_view(), name='featurerequest_detail'),
#     path('featurerequests/create/', views.FeatureRequestCreateView.as_view(), name='featurerequest_create'),
#     path('bugreports/create/', views.BugReportCreateView.as_view(), name='bugreport_create'),
#     path('bugreports/<int:pk_id>/update/', views.BugReportUpdateView.as_view(), name='bugreport_update'),
#     path('bugreports/<int:pk_id>/delete/', views.BugReportDeleteView.as_view(), name='bugreport_delete'),
#     path('featurerequests/<int:pk_id>/update/', views.FeatureRequestUpdateView.as_view(), name='featurerequest_update'),
#     path('featurerequests/<int:pk_id>/delete/', views.FeatureRequestDeleteView.as_view(), name='featurerequest_delete'),
#     ]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

# Class-Based Views (CBV)
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('quality_control/', views.ProjectsListView.as_view(), name='quality_control'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
# #Function-Based Views (FBV)
    # path('', views.index, name='index'),
    # path('quality_control/', views.projects_list, name='quality_control'),
    # path('projects/', views.projects_list, name='projects_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    # path('feedback/', views.feedback_view, name='feedback'),
    # path('projects/new/', views.create_project, name='create_project'),
    # path('projects/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    # path('projects/<int:project_id>/update/', views.update_project, name='update_project'),
    # path('projects/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    # path('projects/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    ]

project_tracker/quality_control/models.py
from django.db import models
from django.utils import timezone
from tasks.models import Project, Task

class BugReport(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True)
    STATUS_CHOICES = [
        ('Новая', 'Новая'),
        ('В работе', 'В работе'),
        ('Завершена', 'Завершена'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)
    priority = models.IntegerField(default=1)  # Добавлено поле priority
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

class FeatureRequest(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True)
    STATUS_CHOICES = [
        ('Рассмотрение', 'Рассмотрение'),
        ('Принято', 'Принято'),
        ('Отклонено', 'Отклонено'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)
    priority = models.IntegerField(default=1)  # Добавлено поле priority
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

project_tracker/quality_control/forms.py
from django.forms import ModelForm
from .models import BugReport, FeatureRequest

class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

project_tracker/quality_control/views.py
#Class-Based Views
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from .models import BugReport, FeatureRequest
from django.shortcuts import render, redirect
from .forms import BugReportForm
from .forms import FeatureRequestForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404

# class IndexView(TemplateView):
#     template_name = 'quality_control/index.html'
#
# class BugReportListView(ListView):
#     model = BugReport
#     template_name = 'quality_control/bugreport_list.html'
#
# class FeatureRequestListView(ListView):
#     model = FeatureRequest
#     template_name = 'quality_control/featurerequest_list.html'
#
# class BugReportDetailView(DetailView):
#     pk_url_kwarg = "pk_id"
#     model = BugReport
#     template_name = 'quality_control/bugreport_detail.html'
#
# class FeatureRequestDetailView(DetailView):
#     pk_url_kwarg = "pk_id"
#     model = FeatureRequest
#     template_name = 'quality_control/featurerequest_detail.html'
#
# class BugReportCreateView(CreateView):
#     model = BugReport
#     template_name = 'quality_control/bug_report_form.html'
#     fields = '__all__'
#     success_url = reverse_lazy('quality_control:index')
#
# class FeatureRequestCreateView(CreateView):
#     model = FeatureRequest
#     template_name = 'quality_control/feature_request_form.html'
#     fields = '__all__'
#     success_url = reverse_lazy('quality_control:index')
# class BugReportUpdateView(UpdateView):
#     model = BugReport
#     form_class = BugReportForm
#     template_name = 'quality_control/bugreport_update.html'
#     pk_url_kwarg = 'pk_id'  # Используем 'pk' вместо 'all'
#     success_url = reverse_lazy('quality_control:index')
#     def get_success_url(self):
#         return reverse_lazy('quality_control:bugreport_detail',
#                             kwargs={'pk_id': self.object.project.id, 'pk_id': self.object.id})
#
# class FeatureRequestUpdateView(UpdateView):
#     model = FeatureRequest
#     form_class = FeatureRequestForm
#     template_name = 'quality_control/featurerequest_update.html'
#     pk_url_kwarg = 'pk_id'  # Используем 'pk' вместо 'all'
#     success_url = reverse_lazy('quality_control:index')
#     def get_success_url(self):
#         return reverse_lazy('quality_control:featurerequest_detail',
#                             kwargs={'pk_id': self.object.project.id, 'pk_id': self.object.id})
#
# class BugReportDeleteView(DeleteView):
#     model = BugReport
#     pk_url_kwarg = 'pk_id'
#     def get_success_url(self):
#         return reverse_lazy('quality_control:bugreport_list')
#
# class FeatureRequestDeleteView(DeleteView):
#     model = FeatureRequest
#     pk_url_kwarg = 'pk_id'
#     def get_success_url(self):
#         return reverse_lazy('quality_control:featurerequest_list')


#Function-Based Views
def index(request):
    return render(request, 'quality_control/index.html')

def bugreport_list(request):
    bugreports = BugReport.objects.all()
    return render(request, 'quality_control/bugreport_list.html', {'bugreport_list': bugreports})
def featurerequest_list(request):
    featurerequests = FeatureRequest.objects.all()
    return render(request, 'quality_control/featurerequest_list.html', {'featurerequest_list': featurerequests})

def bugreport_detail(request, pk_id):
    bugreport = get_object_or_404(BugReport, pk=pk_id)
    return render(request, 'quality_control/bugreport_detail.html', {'bugreport': bugreport, 'pk_id': pk_id})

def featurerequest_detail(request, pk_id):
    featurerequest = get_object_or_404(FeatureRequest, pk=pk_id)
    return render(request, 'quality_control/featurerequest_detail.html', {'featurerequest': featurerequest, 'pk_id': pk_id})

def bugreport_create(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:index')  # Перенаправление на главную страницу после сохранения формы
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html.', {'form': form})
def featurerequest_create(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:index')
    else:
       form = FeatureRequestForm()
       return render(request, 'quality_control/feature_request_form.html', {'form': form})
def bugreport_update(request, pk_id):
    bug_report = get_object_or_404(BugReport, pk=pk_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug_report)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bugreport_detail', pk_id=pk_id)
    else:
        form = BugReportForm(instance=bug_report)
    return render(request, 'quality_control/bug_report_form.html', {'form': form})

def featurerequest_update(request, pk_id):
    feature_request = get_object_or_404(FeatureRequest, pk=pk_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature_request)
        if form.is_valid():
            form.save()
            return redirect('quality_control:featurerequest_detail', pk_id=pk_id)
    else:
        form = FeatureRequestForm(instance=feature_request)
    return render(request, 'quality_control/feature_request_form.html', {'form': form})

def bugreport_delete(request, bugreport_id):
    bug_report = get_object_or_404(BugReport, pk=bugreport_id)
    bug_report.delete()
    return redirect('quality_control:bugreport_list')

def featurerequest_delete(request, pk_id):
    feature_request = get_object_or_404(FeatureRequest, pk=pk_id)
    if request.method == 'POST':
        feature_request.delete()
        return redirect('quality_control:featurerequest_list')
    return render(request, 'quality_control/featurerequest_confirm_delete.html', {'feature_request': feature_request})
def featurerequest_delete(request, featurerequest_id):
    feature_request = get_object_or_404(FeatureRequest, pk=featurerequest_id)
    feature_request.delete()
    return redirect('quality_control:featurerequest_list')

project_tracker/quality_control/templates/quality_control/bug_report_form.html
{% extends "base/base.html" %}

{% block content %}
<h2>Создать новый отчет</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bugreport_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление отчета об ошибке</h1>
    <p>Вы уверены, что хотите удалить отчет "{{ bugreport.title }}"?</p>

     <form action="{% url 'quality_control:bugreport_delete' bugreport.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
         <a href="{% url 'quality_control:bugreport_detail' bugreport.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bugreport_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Детали бага {{ bugreport_id }}</h1>
<p>
    Status: {{ bugreport.status }} <br>
    Priority: {{ bugreport.priority }}<br>
    Description: {{ bugreport.description }}<br>
    Task: {{ bugreport.task }}<br>
    Project: {{ bugreport.project.name }}
</p>
<p><a href="{% url 'quality_control:bugreport_update' bugreport.id %}">Изменить отчет</a></p>
<p><a href="{% url 'quality_control:bugreport_delete' bugreport.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот отчет');">Удалить отчет</a></p>

{% endblock %}

project_tracker/quality_control/templates/quality_control/bugreport_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Cписок отчетов об ошибках</h1>
    <p><a href="{% url 'quality_control:bugreport_create' %}">Создать новый отчет об ошибкe</a></p>
    <ul>
        {% for bugreport in bugreport_list %}
            <p>Title: {{ bugreport.title }}-Status: {{ bugreport.status }}-<a href="{% url 'quality_control:bugreport_detail' bugreport.id %}">Details</a></p>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bugreport_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение : {{ bugreport.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_request_form.html
{% extends "base/base.html" %}

{% block content %}
<h2>Создать запрос на улучшение</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/featurerequest_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос "{{ featurerequest.title }}"?</p>

    <form action="{% url 'quality_control:featurerequest_delete' featurerequest.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:featurerequest_detail' featurerequest.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/featurerequest_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Детали улучшения {{ featurerequest_id }}</h1>
<p>
    Status: {{ featurerequest.status }} <br>
    Priority: {{ featurerequest.priority }}<br>
    Description: {{ featurerequest.description }}<br>
    Task: {{ featurerequest.task }}<br>
    Project: {{ featurerequest.project.name }}
</p>
<p><a href="{% url 'quality_control:featurerequest_update' featurerequest.id %}">Изменить запрос</a></p>
<p><a href="{% url 'quality_control:featurerequest_delete' featurerequest.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот запрос');">Удалить запрос</a></p>

{% endblock %}

project_tracker/quality_control/templates/quality_control/featurerequest_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список запросов на улучшение</h1>
    <p><a href="{% url 'quality_control:featurerequest_create' %}">Создать новый запрос на улучшение</a></p>
    <ul>
        {% for featurerequest in featurerequest_list %}
        <p>Title: {{ featurerequest.title }} - Status: {{ featurerequest.status }} - <a href="{% url 'quality_control:featurerequest_detail' featurerequest.id %}">Details</a></p>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/featurerequest_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение : {{ featurerequest.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
        <h1>Система контроля качества</h1>
        <a href="{% url 'quality_control:bugreport_list' %}">Список всех багов</a>
        <br><a href="{% url 'quality_control:featurerequest_list' %}">Запросы на улучшение</a>
{% endblock %}